# Generated by Django 5.2.15 on 2026-06-25 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(max_length=300, verbose_name='matn (uz)')),
                ('text_ru', models.CharField(blank=True, max_length=300, verbose_name='matn (ru)')),
                ('text_en', models.CharField(blank=True, max_length=300, verbose_name='matn (en)')),
                ('is_correct', models.BooleanField(default=False, verbose_name="to'g'ri")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('title_uz', models.CharField(max_length=120, verbose_name='nomi (uz)')),
                ('title_ru', models.CharField(blank=True, max_length=120, verbose_name='nomi (ru)')),
                ('title_en', models.CharField(blank=True, max_length=120, verbose_name='nomi (en)')),
                ('icon', models.CharField(default='📘', max_length=8, verbose_name='emoji')),
                ('type', models.CharField(choices=[('IT', 'IT (Dasturlash)'), ('School', 'Maktab')], default='IT', max_length=16, verbose_name='tur')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.TextField(verbose_name='savol (uz)')),
                ('text_ru', models.TextField(blank=True, verbose_name='savol (ru)')),
                ('text_en', models.TextField(blank=True, verbose_name='savol (en)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['test', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='nomi (uz)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='nomi (ru)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='nomi (en)')),
                ('subject', models.CharField(blank=True, max_length=64, verbose_name='fan')),
                ('type', models.CharField(default='IT', max_length=16, verbose_name='tur')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='nomi (uz)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='nomi (ru)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='nomi (en)')),
                ('youtube_id', models.CharField(max_length=32, verbose_name='YouTube ID')),
                ('duration', models.CharField(default='15:00', max_length=8, verbose_name='davomiyligi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Qulflangan'), ('watched', "Ko'rildi"), ('passed', 'Topshirildi')], default='locked', max_length=16, verbose_name='holat')),
                ('last_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='oxirgi ball')),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progresslar',
                'ordering': ['-updated_at'],
            },
        ),
    ]
