# Generated by Django 5.2.15 on 2026-07-28 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="narx (so'm)"),
        ),
        migrations.AddField(
            model_name="course",
            name="requires_purchase",
            field=models.BooleanField(
                default=False,
                help_text="Yoqilsa, bu kursning darslari faqat sotib olganlarga ochiladi.",
                verbose_name="alohida sotib olinadi",
            ),
        ),
        migrations.CreateModel(
            name="CoursePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs xaridi",
                "verbose_name_plural": "Kurs xaridlari",
                "ordering": ["-purchased_at"],
                "unique_together": {("user", "course")},
            },
        ),
    ]
