# Generated by Django 5.2.15 on 2026-06-25 19:03

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('student', 'Student'), ('premium', 'Premium')], max_length=16, verbose_name='tarif')),
                ('amount', models.PositiveIntegerField(verbose_name="miqdor (so'm)")),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=apps.payments.models.payment_screenshot_path, verbose_name='chek rasmi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=16, verbose_name='holat')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
