# Generated by Django 5.2.15 on 2026-07-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_price_course_requires_purchase_coursepurchase"),
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="courses.course",
                verbose_name="kurs",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("subscription", "Obuna (tarif)"),
                    ("course", "Kurs sotib olish"),
                ],
                default="subscription",
                max_length=16,
                verbose_name="turi",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="plan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "Free"),
                    ("student", "Student"),
                    ("premium", "Premium"),
                ],
                default="",
                max_length=16,
                verbose_name="tarif",
            ),
        ),
    ]
