# Generated by Django 5.2.15 on 2026-07-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_course_payment_kind_alter_payment_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="duration",
            field=models.CharField(
                blank=True,
                choices=[("week", "1 hafta"), ("month", "1 oy"), ("year", "1 yil")],
                default="",
                max_length=8,
                verbose_name="muddat",
            ),
        ),
    ]
