# Generated by Django 5.2.15 on 2026-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="tarif tugash sanasi"
            ),
        ),
    ]
