# Generated by Django 5.2.15 on 2026-07-14 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nomi")),
                (
                    "icon",
                    models.CharField(default="🎯", max_length=8, verbose_name="emoji"),
                ),
                (
                    "members",
                    models.PositiveIntegerField(default=0, verbose_name="a'zolar soni"),
                ),
                (
                    "schedule",
                    models.CharField(blank=True, max_length=120, verbose_name="jadval"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="tartib"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="aktiv")),
            ],
            options={
                "verbose_name": "To'garak",
                "verbose_name_plural": "To'garaklar",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nomi")),
                (
                    "icon",
                    models.CharField(default="📘", max_length=8, verbose_name="emoji"),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(default=0, verbose_name="progress (%)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="tartib"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="aktiv")),
            ],
            options={
                "verbose_name": "Fan",
                "verbose_name_plural": "Fanlar",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="nomi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("submitted", "Topshirildi"),
                            ("late", "Kechikkan"),
                            ("done", "Bajarildi"),
                            ("in_progress", "Jarayonda"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="holat",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="tartib"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="school.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vazifa",
                "verbose_name_plural": "Vazifalar",
                "ordering": ["order", "id"],
            },
        ),
    ]
