# Generated by Django 5.2.15 on 2026-07-14 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="nomi")),
                (
                    "subject",
                    models.CharField(blank=True, max_length=64, verbose_name="fan"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("IT", "IT"), ("School", "Maktab")],
                        default="IT",
                        max_length=16,
                        verbose_name="tur",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(blank=True, default=list, verbose_name="savollar"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Test",
                "verbose_name_plural": "Testlar (mustaqil)",
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="ball")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="exams.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Natija",
                "verbose_name_plural": "Natijalar",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "test")},
            },
        ),
    ]
