# Generated by Django 5.2.15 on 2026-07-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_price_course_requires_purchase_coursepurchase"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_tests",
                to="courses.course",
                verbose_name="bog'liq kurs",
            ),
        ),
    ]
